title: Nabeel Shah
description: Technical writing on AI systems, models, and engineering.
url: https://sshah41.github.io
baseurl: /articles
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
